version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.0 # Use Node.js version 18.0 for consistency
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test

  build_and_push:
    docker:
      - image: cimg/node:18.0 # Ensure consistency in Node.js version used
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKERHUB_USERNAME/my-unity-web1 .
      - run:
          name: Authenticate with Docker Hub
          command: |
            echo $DOCKERHUB_PASS | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            docker push $DOCKERHUB_USERNAME/my-unity-web1

workflows:
  version: 2.1
  all_tests_and_deploy:
    jobs:
      - build
      - build_and_push:
          requires:
            - build
