version: 2.1

jobs:
  test_cases:
    docker:
      - image: cimg/node:14.17 # Use the official CircleCI Node.js image
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test

  build_and_deploy:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7 # Ensure Docker is available
      - run:
          name: Build Docker Image
          command: |
            docker build -t ${DOCKERHUB_USERNAME}/my-unity-web:v1 .
      - run:
          name: Authenticate with Docker Hub
          command: |
            echo "${DOCKERHUB_PASS}" | docker login --username ${DOCKERHUB_USERNAME} --password-stdin
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            docker push ${DOCKERHUB_USERNAME}/my-unity-web:v1

workflows:
  version: 2
  Test_cases and Auto Deploy:
    jobs:
      - test_cases:
      - build_and_deploy:
          filters:
            branches:
              only: main
