version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.17 # Official CircleCI Node.js image, Node.js version 14.17
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  all_tests:
    jobs:
      - build
